# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wY9-CaXzSeos-GaZ_geyRiGONEDhsjsy
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import plotly.express as px

# =============================
# KONFIGURASI HALAMAN
# =============================
st.set_page_config(
    page_title="Dashboard Motor Bekas",
    layout="wide"
)

st.title("🏍️ Dashboard Analisis Motor Bekas")
st.write(
    "Dashboard ini menampilkan hasil eksplorasi dan analisis data motor bekas "
    "menggunakan **Streamlit**."
)

# =============================
# LOAD DATA
# =============================
DATA_URL = "https://raw.githubusercontent.com/nanocassander-lab/Bekasmotorku/main/motor_second.csv"

@st.cache_data
def load_data():
    return pd.read_csv(DATA_URL)

df = load_data()

# =============================
# SIDEBAR
# =============================
st.sidebar.header("🔍 Filter Data")

st.sidebar.metric("Total Data", df.shape[0])

# Ambil kolom kategorikal & numerik
cat_cols = df.select_dtypes(include=["object"]).columns.tolist()
num_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

# =============================
# FILTER KATEGORIKAL (JIKA ADA)
# =============================
df_filtered = df.copy()

if len(cat_cols) > 0:
    selected_cat = st.sidebar.selectbox(
        "Pilih Kolom Kategori",
        options=cat_cols
    )

    selected_values = st.sidebar.multiselect(
        f"Pilih Nilai {selected_cat}",
        options=df[selected_cat].unique(),
        default=df[selected_cat].unique()
    )

    df_filtered = df_filtered[df_filtered[selected_cat].isin(selected_values)]

# =============================
# FILTER NUMERIK (JIKA ADA)
# =============================
if len(num_cols) > 0:
    selected_num = st.sidebar.selectbox(
        "Pilih Kolom Numerik",
        options=num_cols
    )

    min_val = float(df[selected_num].min())
    max_val = float(df[selected_num].max())

    range_val = st.sidebar.slider(
        "Rentang Nilai",
        min_val,
        max_val,
        (min_val, max_val)
    )

    df_filtered = df_filtered[
        (df_filtered[selected_num] >= range_val[0]) &
        (df_filtered[selected_num] <= range_val[1])
    ]

# =============================
# TAMPILKAN DATA
# =============================
st.subheader("📋 Data Setelah Filter")
st.dataframe(df_filtered, use_container_width=True)

# =============================
# VISUALISASI
# =============================
st.subheader("📊 Visualisasi Data")

col1, col2 = st.columns(2)

if len(num_cols) > 0:
    with col1:
        fig_hist = px.histogram(
            df_filtered,
            x=selected_num,
            nbins=30,
            title=f"Distribusi {selected_num}"
        )
        st.plotly_chart(fig_hist, use_container_width=True)

    with col2:
        fig_box = px.box(
            df_filtered,
            y=selected_num,
            title=f"Boxplot {selected_num}"
        )
        st.plotly_chart(fig_box, use_container_width=True)

# =============================
# STATISTIK
# =============================
if len(num_cols) > 0:
    st.subheader("📈 Statistik Deskriptif")
    st.write(df_filtered[selected_num].describe())

# =============================
# FOOTER
# =============================
st.markdown("---")
st.caption("Dibuat menggunakan Streamlit • Data Motor Bekas")